import type { Metadata } from 'next';
import { Inter, Geist_Mono, Geist } from 'next/font/google';
import '../styles/globals.css';
import { cn } from "@/src/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="pt-BR"
            className={cn("h-full", "antialiased", inter.variable, geistMono.variable, "font-sans", geist.variable)}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
